language : php

php:
- 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
matrix:
   allow_failures:
    - php: nightly
    - php: hhvm
  
before_script: composer install
  
script : phpunit --configuration phpunit.xml